# Makefile to coordinate infra build and deploy
.PHONY: infra build deploy all kubeconfig

infra:
	./scripts/apply_terraform.sh --auto-approve

build:
	IMAGE_TAG=${IMAGE_TAG:-latest} ECR_REGISTRY=${ECR_REGISTRY} ECR_REPO=${ECR_REPO} ./scripts/build_push.sh

kubeconfig:
	./scripts/generate_kubeconfig.sh

deploy:
	# requires IMAGE or ECR_REGISTRY/ECR_REPO and KUBECONFIG (generated by kubeconfig target)
	IMAGE=${IMAGE} ECR_REGISTRY=${ECR_REGISTRY} ECR_REPO=${ECR_REPO} IMAGE_TAG=${IMAGE_TAG} ./scripts/deploy.sh

all: infra build kubeconfig deploy
	@echo "All done"
